-- lua_webp test suite. Run with `make test` (or directly: lua5.4 tests/test.lua).

local function assert_eq(actual, expected, msg)
  if actual ~= expected then
    error((msg or "assert_eq failed") .. string.format(": expected %s, got %s",
          tostring(expected), tostring(actual)), 2)
  end
end

local function assert_error(pattern, fn)
  local ok, err = pcall(fn)
  if ok then
    error("expected error matching " .. pattern, 2)
  end
  if not tostring(err):match(pattern) then
    error(string.format("expected error matching %q, got %q", pattern, tostring(err)), 2)
  end
end

local function read_file(path)
  local f = assert(io.open(path, "rb"), "cannot open " .. path)
  local data = f:read("*a")
  f:close()
  return data
end

local function is_webp(s)
  return s:sub(1, 4) == "RIFF" and s:sub(9, 12) == "WEBP"
end

local function is_png(s)
  return s:sub(1, 8) == "\137PNG\r\n\26\n"
end

-- Returns width, height, color type from a PNG IHDR chunk.
local function png_ihdr(s)
  local function be32(i)
    return s:byte(i) * 16777216 + s:byte(i + 1) * 65536 +
           s:byte(i + 2) * 256 + s:byte(i + 3)
  end
  return be32(17), be32(21), s:byte(26)
end

local webp = require("lua_webp")
assert_eq(type(webp), "table", "module must load")
assert_eq(type(webp.cwebp), "userdata", "cwebp handle")
assert_eq(type(webp.dwebp), "userdata", "dwebp handle")

local cwebp = webp.cwebp
local dwebp = webp.dwebp

-- Fixture: 16x16 RGBA image generated by tools/gen_fixtures.c.
--   R = x*16+3, G = y*16+7, B = ((x+y)%2)?200:40, A = ((x+y)%3)?255:128
local png_data = read_file("tests/fixture.png")
local webp_data = read_file("tests/fixture.webp")
local jpg_data = read_file("tests/fixture.jpg")

-- ---------------------------------------------------------------------------
-- Encoding (cwebp)
-- ---------------------------------------------------------------------------

local out = cwebp:image2Webp(png_data)
assert(is_webp(out), "image2Webp must return webp bytes")

local out2 = cwebp:path2Webp("tests/fixture.png")
assert(is_webp(out2), "path2Webp must return webp bytes")

-- JPEG input from a real photo
local jw = cwebp:image2Webp(jpg_data, { quality = 75 })
assert(is_webp(jw), "image2Webp(jpeg) must return webp bytes")
local jw2 = cwebp:path2Webp("tests/fixture.jpg", { quality = 75 })
assert(is_webp(jw2), "path2Webp(jpeg) must return webp bytes")

-- Lossy quality must affect the output size
local q10 = cwebp:image2Webp(jpg_data, { quality = 10 })
local q90 = cwebp:image2Webp(jpg_data, { quality = 90 })
assert(is_webp(q10) and is_webp(q90), "quality variants must be webp")
assert(#q10 < #q90, "lower quality must produce a smaller file")

-- Default config (no table) must work too
assert(is_webp(cwebp:image2Webp(png_data, nil)), "nil config is accepted")
assert(is_webp(cwebp:image2Webp(png_data, {})), "empty config is accepted")

-- TIFF input (tests/fixture.tiff, 16x16 RGBA from gen_fixtures)
local tiff_data = read_file("tests/fixture.tiff")
local tiff_out = cwebp:image2Webp(tiff_data, { lossless = 1 })
assert(is_webp(tiff_out), "image2Webp(tiff) must return webp bytes")
assert_eq(dwebp:info(tiff_out).width, 16, "tiff input width")
assert_eq(dwebp:info(tiff_out).height, 16, "tiff input height")
assert_eq(dwebp:info(tiff_out).has_alpha, true, "tiff input alpha")

-- PNM inputs built by hand: PPM (P6), PGM (P5), PAM (P7)
local ppm_in = "P6\n2 2\n255\n" .. string.rep("\200\100\50", 4)
local ppm_out = cwebp:image2Webp(ppm_in)
assert(is_webp(ppm_out), "image2Webp(ppm) must return webp bytes")
assert_eq(dwebp:info(ppm_out).width, 2, "ppm input width")

local pgm_in = "P5\n2 2\n255\n" .. string.rep("\128", 4)
assert(is_webp(cwebp:image2Webp(pgm_in)), "image2Webp(pgm) must return webp bytes")

local pam_in = "P7\nWIDTH 2\nHEIGHT 2\nDEPTH 4\nMAXVAL 255\n" ..
  "TUPLTYPE RGB_ALPHA\nENDHDR\n" .. string.rep("\1\2\3\255", 4)
assert(is_webp(cwebp:image2Webp(pam_in)), "image2Webp(pam) must return webp bytes")

-- WebP input re-encode
local webp_in = cwebp:image2Webp(webp_data, { lossless = 1 })
assert(is_webp(webp_in), "image2Webp(webp) must return webp bytes")
assert_eq(dwebp:info(webp_in).width, 16, "webp input width")
assert_eq(dwebp:info(webp_in).format, "lossless", "webp re-encode stays lossless")

-- image_hint accepts strings and raw WEBP_HINT_* integers
assert(is_webp(cwebp:image2Webp(png_data, { image_hint = "photo" })),
       "image_hint photo")
assert(is_webp(cwebp:image2Webp(png_data, { image_hint = "picture" })),
       "image_hint picture")
assert(is_webp(cwebp:image2Webp(png_data, { image_hint = "graph" })),
       "image_hint graph")
assert(is_webp(cwebp:image2Webp(png_data, { image_hint = 2 })),
       "image_hint raw integer")

-- Every config field accepted at once (lossless encode ignores most of them)
local full_config = {
  lossless = 1, quality = 90, method = 4, target_size = 0,
  target_PSNR = 0, segments = 4, sns_strength = 50,
  filter_strength = 60, filter_sharpness = 3, filter_type = 1,
  autofilter = 1, alpha_compression = 1, alpha_filtering = 2,
  alpha_quality = 80, pass = 3, show_compressed = 0,
  preprocessing = 0, partitions = 0, partition_limit = 0,
  emulate_jpeg_size = 0, thread_level = 1, low_memory = 0,
  near_lossless = 50, exact = 1, use_delta_palette = 0,
  use_sharp_yuv = 0, qmin = 0, qmax = 100,
}
assert(is_webp(cwebp:image2Webp(png_data, full_config)), "full config accepted")

-- Lossless round-trip: encode lossless, decode to PPM, compare pixels exactly
local lossless = cwebp:image2Webp(png_data, { lossless = 1 })
assert(is_webp(lossless), "lossless encode must return webp bytes")

local ppm = dwebp:webp2Image(lossless, "ppm")
local header_end = ppm:find("\n255\n", 1, true)
assert(header_end, "ppm must have a header")
local pixels = ppm:sub(header_end + 5)
assert_eq(#pixels, 16 * 16 * 3, "ppm pixel count (RGB)")
for y = 0, 15 do
  for x = 0, 15 do
    local i = (y * 16 + x) * 3 + 1
    local r, g, b = pixels:byte(i), pixels:byte(i + 1), pixels:byte(i + 2)
    assert_eq(r, x * 16 + 3, "lossless R round-trip")
    assert_eq(g, y * 16 + 7, "lossless G round-trip")
    assert_eq(b, ((x + y) % 2) == 1 and 200 or 40, "lossless B round-trip")
  end
end

-- Alpha must survive the lossless round-trip (PAM = RGBA)
local pam = dwebp:webp2Image(lossless, "pam")
local pam_end = pam:find("ENDHDR\n", 1, true)
assert(pam_end, "pam must have a header")
local pam_pixels = pam:sub(pam_end + 7)
assert_eq(#pam_pixels, 16 * 16 * 4, "pam pixel count (RGBA)")
for y = 0, 15 do
  for x = 0, 15 do
    local a = pam_pixels:byte((y * 16 + x) * 4 + 4)
    assert_eq(a, ((x + y) % 3) == 0 and 128 or 255, "lossless alpha round-trip")
  end
end

-- ---------------------------------------------------------------------------
-- Decoding (dwebp)
-- ---------------------------------------------------------------------------

-- PNG output: dimensions and color type (RGBA because the fixture has alpha)
local png_out = dwebp:webp2Image(webp_data, "png")
assert(is_png(png_out), "webp2Image png must be a png")
local pw, ph, pct = png_ihdr(png_out)
assert_eq(pw, 16, "png width")
assert_eq(ph, 16, "png height")
assert_eq(pct, 6, "png color type must be RGBA (6)")

-- Forced colorspaces are exported as raw, tightly packed pixel bytes
-- plus their dimensions: RGB drops alpha (3 bytes/px), RGBA keeps it.
local rgb, rw, rh = dwebp:webp2Image(webp_data, "RGB")
assert_eq(rw, 16, "RGB raw width")
assert_eq(rh, 16, "RGB raw height")
assert_eq(#rgb, 16 * 16 * 3, "RGB raw byte count")
assert_eq(rgb:byte(1), 3, "RGB first pixel R")
assert_eq(rgb:byte(2), 7, "RGB first pixel G")
assert_eq(rgb:byte(3), 40, "RGB first pixel B")

local rgba, arw, arh = dwebp:webp2Image(webp_data, "RGBA")
assert_eq(arw, 16, "RGBA raw width")
assert_eq(arh, 16, "RGBA raw height")
assert_eq(#rgba, 16 * 16 * 4, "RGBA raw byte count")
-- fixture alpha: A = ((x+y)%3 == 0) and 128 or 255
assert_eq(rgba:byte(4), 128, "RGBA first pixel alpha")
assert_eq(rgba:byte(4 + 4 + 4 + 4 + 4), 255, "RGBA second pixel alpha")

local bgr = dwebp:webp2Image(webp_data, "BGR")
assert_eq(#bgr, 16 * 16 * 3, "BGR raw byte count")
assert_eq(bgr:byte(1), 40, "BGR first pixel B")
assert_eq(bgr:byte(3), 3, "BGR first pixel R")

local rgb565 = dwebp:webp2Image(webp_data, "RGB_565")
assert_eq(#rgb565, 16 * 16 * 2, "RGB_565 raw byte count")

-- 16-bit forced colorspaces: non-zero packed first pixel (byte-order
-- independent)
local rgba4444 = dwebp:webp2Image(webp_data, "RGBA_4444")
assert_eq(#rgba4444, 16 * 16 * 2, "RGBA_4444 byte count")
assert(rgba4444:byte(1) ~= 0 or rgba4444:byte(2) ~= 0,
       "RGBA_4444 first pixel non-zero")
local rgbA4444 = dwebp:webp2Image(webp_data, "rgbA_4444")
assert_eq(#rgbA4444, 16 * 16 * 2, "rgbA_4444 byte count")

-- YUVA has extra alpha planes vs plain YUV (lossy fixture has no alpha)
local yuv_noa = dwebp:webp2Image(q10, "yuv")
local yuva_noa = dwebp:webp2Image(q10, "yuva")
assert(#yuva_noa > #yuv_noa, "yuva must be larger than yuv")

-- Cropping combined with a forced colorspace
local cropped_rgba, cw, ch = dwebp:webp2Image(webp_data, "RGBA", {
  use_cropping = 1, crop_left = 0, crop_top = 0,
  crop_width = 8, crop_height = 8,
})
assert_eq(cw, 8, "crop RGBA width")
assert_eq(ch, 8, "crop RGBA height")
assert_eq(#cropped_rgba, 8 * 8 * 4, "crop RGBA byte count")

-- path2Image with a forced colorspace
local prgba, pw2, ph2 = dwebp:path2Image("tests/fixture.webp", "RGBA")
assert_eq(pw2, 16, "path2Image RGBA width")
assert_eq(ph2, 16, "path2Image RGBA height")
assert_eq(#prgba, 16 * 16 * 4, "path2Image RGBA byte count")

-- More decoder options must not break output
assert(is_png(dwebp:webp2Image(webp_data, "png", { dithering_strength = 50 })),
       "dithering_strength option")
assert(is_png(dwebp:webp2Image(webp_data, "png", { no_fancy_upsampling = 1 })),
       "no_fancy_upsampling option")
assert(is_png(dwebp:webp2Image(webp_data, "png", { bypass_filtering = 1 })),
       "bypass_filtering option")

-- path2Image matches webp2Image
local png_from_path = dwebp:path2Image("tests/fixture.webp", "png")
assert(is_png(png_from_path), "path2Image png must be a png")
local iw, ih, ict = png_ihdr(png_from_path)
assert_eq(iw, 16, "path2Image width")
assert_eq(ih, 16, "path2Image height")
assert_eq(ict, 6, "path2Image color type")

-- Other container formats
local bmp = dwebp:webp2Image(webp_data, "bmp")
assert_eq(bmp:sub(1, 2), "BM", "bmp magic")
local tiff = dwebp:webp2Image(webp_data, "tiff")
assert_eq(tiff:sub(1, 4), "II*\0", "tiff magic (little endian)")
local yuv = dwebp:webp2Image(webp_data, "yuv")
-- exact size is decoder-stride dependent; require at least the luma plane
assert(#yuv > 16 * 16, "raw yuv must contain the luma plane")
local pgm = dwebp:webp2Image(webp_data, "pgm")
assert(pgm:match("^P5\n"), "pgm magic")

-- Decoder options: cropping and scaling
local cropped = dwebp:webp2Image(webp_data, "ppm", {
  use_cropping = 1, crop_left = 0, crop_top = 0,
  crop_width = 8, crop_height = 8,
})
assert(cropped:match("P6\n8 8\n255\n"), "crop must produce an 8x8 ppm")

local scaled = dwebp:webp2Image(webp_data, "ppm", {
  use_scaling = 1, scaled_width = 32, scaled_height = 32,
})
assert(scaled:match("P6\n32 32\n255\n"), "scale must produce a 32x32 ppm")

-- flip moves the last source row to the first output row (G = y*16+7)
local flipped = dwebp:webp2Image(webp_data, "ppm", { flip = 1 })
local fh = flipped:find("\n255\n", 1, true)
assert(fh, "flip ppm header")
assert_eq(flipped:sub(fh + 5):byte(2), 15 * 16 + 7, "flip first row G")

-- alpha plane output (ALPHA_PLANE_ONLY): PGM header + raw alpha bytes
local alpha = dwebp:webp2Image(webp_data, "alpha")
assert(alpha:match("^P5\n"), "alpha plane pgm magic")
local ah = alpha:find("\n255\n", 1, true)
assert_eq(#alpha - (ah + 4), 16 * 16, "alpha plane byte count")
assert_eq(alpha:byte(ah + 5), 128, "first pixel alpha (x+y=0)")
assert_eq(alpha:byte(ah + 6), 255, "second pixel alpha (x+y=1)")

-- RGB_565 packed value for fixture pixel (0,0): R=3,G=7,B=40
-- -> R5=(3>>3)=0, G6=(7>>2)=1, B5=(40>>3)=5 => 16-bit value 37.
-- The byte order depends on libwebp's WEBP_SWAP_16BIT_CSP build option
-- (OFF on Linux/vendored, ON on some MSYS2 builds), so accept either.
local rgb565_px = dwebp:webp2Image(webp_data, "RGB_565")
assert_eq(#rgb565_px, 16 * 16 * 2, "RGB_565 raw byte count")
local lo, hi = rgb565_px:byte(1), rgb565_px:byte(2)
assert((lo == 37 and hi == 0) or (lo == 0 and hi == 37),
       "RGB_565 first pixel must pack value 37")

local threaded = dwebp:webp2Image(webp_data, "png", { use_threads = 1 })
assert(is_png(threaded), "use_threads must not break output")

-- Lossy webp decodes fine too
assert(is_png(dwebp:webp2Image(q10, "png")), "lossy webp must decode to png")

-- ---------------------------------------------------------------------------
-- Info and version
-- ---------------------------------------------------------------------------

local info = dwebp:info(webp_data)
assert_eq(type(info), "table", "info must return a table")
assert_eq(info.width, 16, "info width")
assert_eq(info.height, 16, "info height")
assert_eq(info.has_alpha, true, "info has_alpha")
assert_eq(info.format, "lossless", "info format")

local info2 = dwebp:infoFromPath("tests/fixture.webp")
assert_eq(info2.width, 16, "infoFromPath width")
assert_eq(info2.height, 16, "infoFromPath height")
assert_eq(info2.format, "lossless", "infoFromPath format")

local lossy_info = dwebp:info(q10)
assert_eq(lossy_info.format, "lossy", "lossy info format")
assert_eq(lossy_info.has_alpha, false, "lossy jpeg has no alpha")

local v = webp.version()
assert_eq(type(v), "table", "version must return a table")
assert(v.encoder:match("^%d+%.%d+%.%d+$"), "encoder version string")
assert(v.decoder:match("^%d+%.%d+%.%d+$"), "decoder version string")

-- ---------------------------------------------------------------------------
-- Error handling
-- ---------------------------------------------------------------------------

assert_error("bad argument", function() cwebp:path2Webp() end)
assert_error("bad argument", function() cwebp:image2Webp() end)
assert_error("bad argument", function() cwebp:image2Webp(png_data, "not-a-table") end)
assert_error("unknown config field", function()
  cwebp:image2Webp(png_data, { bogus_field = 1 })
end)
assert_error("must be numeric", function()
  cwebp:image2Webp(png_data, { quality = "high" })
end)
assert_error("invalid WebP configuration", function()
  cwebp:image2Webp(png_data, { quality = 500 })
end)
assert_error("failed to read", function() cwebp:path2Webp("tests/does-not-exist.png") end)
assert_error("corrupt", function() cwebp:image2Webp("this is not an image at all") end)

assert_error("bad argument", function() dwebp:webp2Image(webp_data) end)
assert_error("unknown output format", function() dwebp:webp2Image(webp_data, "jpg") end)
assert_error("corrupt", function() dwebp:webp2Image("definitely not webp data", "png") end)
assert_error("unknown option", function()
  dwebp:webp2Image(webp_data, "png", { bogus_option = 1 })
end)
assert_error("failed to load", function()
  dwebp:path2Image("tests/does-not-exist.webp", "png")
end)
assert_error("corrupt", function() dwebp:info("not webp data") end)
assert_error("failed to load", function()
  dwebp:infoFromPath("tests/does-not-exist.webp")
end)

-- Non-string keys in config/options tables
assert_error("keys must be strings", function()
  cwebp:image2Webp(png_data, { [1] = 2 })
end)
assert_error("keys must be strings", function()
  dwebp:webp2Image(webp_data, "png", { [1] = 2 })
end)

-- Empty input data
assert_error("corrupt", function() cwebp:image2Webp("") end)
assert_error("corrupt", function() dwebp:webp2Image("", "png") end)

-- image_hint with an unknown string
assert_error("image_hint", function()
  cwebp:image2Webp(png_data, { image_hint = "bogus" })
end)

print("lua_webp tests passed")
