-- lua_webp test suite. Run with `make test` (or directly: lua5.4 tests/test.lua).

local function assert_eq(actual, expected, msg)
  if actual ~= expected then
    error((msg or "assert_eq failed") .. string.format(": expected %s, got %s",
          tostring(expected), tostring(actual)), 2)
  end
end

local function assert_error(pattern, fn)
  local ok, err = pcall(fn)
  if ok then
    error("expected error matching " .. pattern, 2)
  end
  if not tostring(err):match(pattern) then
    error(string.format("expected error matching %q, got %q", pattern, tostring(err)), 2)
  end
end

local function read_file(path)
  local f = assert(io.open(path, "rb"), "cannot open " .. path)
  local data = f:read("*a")
  f:close()
  return data
end

local function is_webp(s)
  return s:sub(1, 4) == "RIFF" and s:sub(9, 12) == "WEBP"
end

local function is_png(s)
  return s:sub(1, 8) == "\137PNG\r\n\26\n"
end

-- Returns width, height, color type from a PNG IHDR chunk.
local function png_ihdr(s)
  local function be32(i)
    return s:byte(i) * 16777216 + s:byte(i + 1) * 65536 +
           s:byte(i + 2) * 256 + s:byte(i + 3)
  end
  return be32(17), be32(21), s:byte(26)
end

local webp = require("lua_webp")
assert_eq(type(webp), "table", "module must load")
assert_eq(type(webp.cwebp), "userdata", "cwebp handle")
assert_eq(type(webp.dwebp), "userdata", "dwebp handle")

local cwebp = webp.cwebp
local dwebp = webp.dwebp

-- Fixture: 16x16 RGBA image generated by tools/gen_fixtures.c.
--   R = x*16+3, G = y*16+7, B = ((x+y)%2)?200:40, A = ((x+y)%3)?255:128
local png_data = read_file("tests/fixture.png")
local webp_data = read_file("tests/fixture.webp")
local jpg_data = read_file("tests/fixture.jpg")

-- ---------------------------------------------------------------------------
-- Encoding (cwebp)
-- ---------------------------------------------------------------------------

local out = cwebp:image2Webp(png_data)
assert(is_webp(out), "image2Webp must return webp bytes")

local out2 = cwebp:path2Webp("tests/fixture.png")
assert(is_webp(out2), "path2Webp must return webp bytes")

-- JPEG input from a real photo
local jw = cwebp:image2Webp(jpg_data, { quality = 75 })
assert(is_webp(jw), "image2Webp(jpeg) must return webp bytes")
local jw2 = cwebp:path2Webp("tests/fixture.jpg", { quality = 75 })
assert(is_webp(jw2), "path2Webp(jpeg) must return webp bytes")

-- Lossy quality must affect the output size
local q10 = cwebp:image2Webp(jpg_data, { quality = 10 })
local q90 = cwebp:image2Webp(jpg_data, { quality = 90 })
assert(is_webp(q10) and is_webp(q90), "quality variants must be webp")
assert(#q10 < #q90, "lower quality must produce a smaller file")

-- Default config (no table) must work too
assert(is_webp(cwebp:image2Webp(png_data, nil)), "nil config is accepted")
assert(is_webp(cwebp:image2Webp(png_data, {})), "empty config is accepted")

-- Lossless round-trip: encode lossless, decode to PPM, compare pixels exactly
local lossless = cwebp:image2Webp(png_data, { lossless = 1 })
assert(is_webp(lossless), "lossless encode must return webp bytes")

local ppm = dwebp:webp2Image(lossless, "ppm")
local header_end = ppm:find("\n255\n", 1, true)
assert(header_end, "ppm must have a header")
local pixels = ppm:sub(header_end + 5)
assert_eq(#pixels, 16 * 16 * 3, "ppm pixel count (RGB)")
for y = 0, 15 do
  for x = 0, 15 do
    local i = (y * 16 + x) * 3 + 1
    local r, g, b = pixels:byte(i), pixels:byte(i + 1), pixels:byte(i + 2)
    assert_eq(r, x * 16 + 3, "lossless R round-trip")
    assert_eq(g, y * 16 + 7, "lossless G round-trip")
    assert_eq(b, ((x + y) % 2) == 1 and 200 or 40, "lossless B round-trip")
  end
end

-- Alpha must survive the lossless round-trip (PAM = RGBA)
local pam = dwebp:webp2Image(lossless, "pam")
local pam_end = pam:find("ENDHDR\n", 1, true)
assert(pam_end, "pam must have a header")
local pam_pixels = pam:sub(pam_end + 7)
assert_eq(#pam_pixels, 16 * 16 * 4, "pam pixel count (RGBA)")
for y = 0, 15 do
  for x = 0, 15 do
    local a = pam_pixels:byte((y * 16 + x) * 4 + 4)
    assert_eq(a, ((x + y) % 3) == 0 and 128 or 255, "lossless alpha round-trip")
  end
end

-- ---------------------------------------------------------------------------
-- Decoding (dwebp)
-- ---------------------------------------------------------------------------

-- PNG output: dimensions and color type (RGBA because the fixture has alpha)
local png_out = dwebp:webp2Image(webp_data, "png")
assert(is_png(png_out), "webp2Image png must be a png")
local pw, ph, pct = png_ihdr(png_out)
assert_eq(pw, 16, "png width")
assert_eq(ph, 16, "png height")
assert_eq(pct, 6, "png color type must be RGBA (6)")

-- Forced colorspaces: "RGB" is dumped as raw PPM (alpha dropped),
-- "RGBA" is saved as PNG like the dwebp reference tool.
local rgb_ppm = dwebp:webp2Image(webp_data, "RGB")
local rgb_hdr = rgb_ppm:find("\n255\n", 1, true)
assert(rgb_hdr, "RGB format must produce a ppm")
assert(rgb_ppm:match("P6\n16 16\n255\n"), "RGB ppm header")
assert_eq(#rgb_ppm - (rgb_hdr + 4), 16 * 16 * 3, "RGB ppm pixel count")

local rgba_png = dwebp:webp2Image(webp_data, "RGBA")
assert(is_png(rgba_png), "RGBA format must produce a png")
local arw, arh, arct = png_ihdr(rgba_png)
assert_eq(arw, 16, "RGBA png width")
assert_eq(arh, 16, "RGBA png height")
assert_eq(arct, 6, "RGBA png color type")

-- path2Image matches webp2Image
local png_from_path = dwebp:path2Image("tests/fixture.webp", "png")
assert(is_png(png_from_path), "path2Image png must be a png")
local iw, ih, ict = png_ihdr(png_from_path)
assert_eq(iw, 16, "path2Image width")
assert_eq(ih, 16, "path2Image height")
assert_eq(ict, 6, "path2Image color type")

-- Other container formats
local bmp = dwebp:webp2Image(webp_data, "bmp")
assert_eq(bmp:sub(1, 2), "BM", "bmp magic")
local tiff = dwebp:webp2Image(webp_data, "tiff")
assert_eq(tiff:sub(1, 4), "II*\0", "tiff magic (little endian)")
local yuv = dwebp:webp2Image(webp_data, "yuv")
-- exact size is decoder-stride dependent; require at least the luma plane
assert(#yuv > 16 * 16, "raw yuv must contain the luma plane")
local pgm = dwebp:webp2Image(webp_data, "pgm")
assert(pgm:match("^P5\n"), "pgm magic")

-- Decoder options: cropping and scaling
local cropped = dwebp:webp2Image(webp_data, "ppm", {
  use_cropping = 1, crop_left = 0, crop_top = 0,
  crop_width = 8, crop_height = 8,
})
assert(cropped:match("P6\n8 8\n255\n"), "crop must produce an 8x8 ppm")

local scaled = dwebp:webp2Image(webp_data, "ppm", {
  use_scaling = 1, scaled_width = 32, scaled_height = 32,
})
assert(scaled:match("P6\n32 32\n255\n"), "scale must produce a 32x32 ppm")

local threaded = dwebp:webp2Image(webp_data, "png", { use_threads = 1 })
assert(is_png(threaded), "use_threads must not break output")

-- Lossy webp decodes fine too
assert(is_png(dwebp:webp2Image(q10, "png")), "lossy webp must decode to png")

-- ---------------------------------------------------------------------------
-- Error handling
-- ---------------------------------------------------------------------------

assert_error("bad argument", function() cwebp:path2Webp() end)
assert_error("bad argument", function() cwebp:image2Webp() end)
assert_error("bad argument", function() cwebp:image2Webp(png_data, "not-a-table") end)
assert_error("unknown config field", function()
  cwebp:image2Webp(png_data, { bogus_field = 1 })
end)
assert_error("must be a number", function()
  cwebp:image2Webp(png_data, { quality = "high" })
end)
assert_error("invalid WebP configuration", function()
  cwebp:image2Webp(png_data, { quality = 500 })
end)
assert_error("failed to read", function() cwebp:path2Webp("tests/does-not-exist.png") end)
assert_error("corrupt", function() cwebp:image2Webp("this is not an image at all") end)

assert_error("bad argument", function() dwebp:webp2Image(webp_data) end)
assert_error("unknown output format", function() dwebp:webp2Image(webp_data, "jpg") end)
assert_error("corrupt", function() dwebp:webp2Image("definitely not webp data", "png") end)
assert_error("unknown option", function()
  dwebp:webp2Image(webp_data, "png", { bogus_option = 1 })
end)
assert_error("failed to load", function()
  dwebp:path2Image("tests/does-not-exist.webp", "png")
end)

print("lua_webp tests passed")
